name: menu_loyalty
description: Delivery app for restaurants with loyalty program
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Auto-gen
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

  #Flutter Localizations
  flutter_localizations:
    sdk: flutter  
  intl: ^0.19.0

  # Firebase
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4

  # State Management
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.1.0
  provider: ^6.0.3


  # UI
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^6.2.1
  ionicons: ^0.2.2
  modal_bottom_sheet: ^3.0.0
  progress_indicators: ^1.0.0

  # Utils
  equatable: ^2.0.3
  dartz: ^0.10.1
  go_router: ^14.2.3


dev_dependencies:
  build_runner: ^2.1.11
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  go_router_builder: ^2.5.1
  json_serializable: ^6.2.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic